import MainLayout from '@/component/layout/main-layout';
import './global.css';
import { Providers } from '@/component/layout/providers';

export const metadata = {
  title: 'Care Now Take Home Test',
  description: 'Generated by Maulana Akbar Yudistika',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );
}
