import './global.css';

export const metadata = {
  title: 'Care Now Take Home Test',
  description: 'Generated by Maulana Akbar Yudistika',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
